#!/bin/sh
set -e

bundle install

./bin/rails db:prepare
./bin/rails db:test:prepare

yarn build
yarn build:css

echo "🚀 Ready to rock!
Run these commadns in separate terminal windows:
anycable-go
./bin/rails server"
